#!/bin/sh

cd $HOME
ln -s .dotfiles/.gitconfig
ln -s .dotfiles/.gitignore.global .gitignore
ln -s .dotfiles/.tmux.conf
ln -s .dotfiles/.vimrc
ln -s .dotfiles/.vimshrc
ln -s .dotfiles/.zsh
ln -s .dotfiles/.zshrc
ln -s .dotfiles/bin/tmuxx /usr/local/bin/tmuxx

if [ ! -d $HOME/.tmux ]; then
    if which git > /dev/null 2>&1; then
        mkdir .tmux
        git clone https://github.com/erikw/tmux-powerline.git ~/.tmux/tmux-powerline
    else
        echo 'command git is not exist. install git first.' >&2
    fi
fi
